export enum UserRoleEnum {
  SUPER_ADMIN = 'SUPER_ADMIN',
  CASE_MANAGER = 'CASE_MANAGER',
  CLIENT = 'CLIENT'
}

export enum AppointmentStatusesEnum {
  UPCOMING = 'UPCOMING',
  ACKNOWLEDGED = 'ACKNOWLEDGED',
  DECLINED = 'DECLINED',
  APPEARED = 'APPEARED',
  ABSENT = 'ABSENT'
}

export enum AppointmentTypeEnum {
  COURT = 'COURT',
  APPEARANCE = 'APPEARANCE',
  MANDATED_CLASS = 'MANDATED_CLASS'
}
